System:
  Setup: true

  QuickSetup:
    Enable: false
    Currency:
      Name: Dollar
      NamePlural: Dollars
      Minor: Coin
      MinorPlural: Coins
      Sign: $
    StartBalance: 100.0
    PriceBank: 200.0
    #Available values: Long, small, majoronly, sign
    DisplayMode: long

  CheckNewVersion: true
  Case-sentitive: false
  CreateOnLogin: false

  # Logs all monetary transactions passed through CraftConomy in a table.
  Logging:
    Enabled: false
    
  Database:
    # Databases Supported:
    ##
    # mysql
    #  - These will attempt to connect to MySQL
    ##
    # h2
    #  - These will attempt to create & connect to H2
    Type: 'h2'
    
    #Modify if using MySQL
    Address: 'localhost'
    Port: 3306
    Username: 'root'
    Password: ''
    Db: 'Craftconomy'
    Prefix: 'cc3_'

    #Used when you come from H2 and want a MySQL database
    ConvertFromSQLite: false

    #the database revision
    dbVersion: 0
